# The directory where models and summaries will be saved. It is created if it does not exist.
model_dir: eval_dir

data:
  # (required for train_end_eval and eval run types).
  eval_features_file: data/processed/heron/eval_inputs.txt
  eval_labels_file: data/processed/heron/eval_targets.txt
  
# Model and optimization parameters.
params:

# (optional) Evaluation options.
eval:
  # (optional) Save evaluation predictions in model_dir/eval/.
  save_eval_predictions: true
  # (optional) Evalutator or list of evaluators that are called on the saved evaluation predictions.
  # Available evaluators: BLEU, BLEU-detok, ROUGE
  external_evaluators: [BLEU, BLEU-detok, ROUGE]
  # (optional) Model exporter(s) to use during the training and evaluation loop:
  # last, final, best, or null (default: last).
  exporters: last

# (optional) Inference options.
infer:
  # (optional) The batch size to use (default: 1).
  batch_size: 16
  # (optional) For compatible models, the number of hypotheses to output (default: 1).
  n_best: 1

# (optional) Scoring options.
score:
  # (optional) The batch size to use (default: 64).
  batch_size: 64