# The directory where models and summaries will be saved. It is created if it does not exist.
model_dir: adhoc

data:
  train_features_file: data/processed/heron/train_inputs.txt
  train_labels_file: data/processed/heron/train_targets.txt
  
  eval_features_file: data/processed/heron/eval_inputs.txt
  eval_labels_file: data/processed/heron/eval_targets.txt
  
  source_words_vocabulary: data/processed/heron/vocab.txt
  target_words_vocabulary: data/processed/heron/vocab.txt
  
# Model and optimization parameters.
params:

eval:
  save_eval_predictions: true
  external_evaluators: [BLEU, ROUGE]
  exporters: last
  batch_size: 32
  num_threads: 1
  prefetch_buffer_size: 1